# Configuração do Apache para a aplicação __HOSTNAME__
# /etc/apache2/sites-available/__HOSTNAME__.conf

<VirtualHost *:80>
    ServerName __HOSTNAME__

    DocumentRoot /var/www/__HOSTNAME__

    RewriteEngine On

    # --- REGRAS DE PROXY REVERSO ---
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule ^/ws(.*) ws://127.0.0.1:8000/ws$1 [P,L]

    # Redireciona todas as chamadas para /api para o backend
    RewriteRule ^/api(.*) http://127.0.0.1:8000/api$1 [P,L]


    # --- REGRA PARA SERVIR O FRONTEND (SINGLE PAGE APPLICATION) ---
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -f [OR]
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]

    RewriteRule ^ /index.html [L]


    # --- Configurações de Diretório e Logs ---
    <Directory /var/www/__HOSTNAME__>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/__HOSTNAME___error.log
    CustomLog ${APACHE_LOG_DIR}/__HOSTNAME___access.log combined

</VirtualHost>
